version: '3.8'

services:
  handytime:
    build:
      context: .
      dockerfile: Dockerfile
    image: handytime:latest
    container_name: handytime_app
    ports:
      - "3001:3001"
    restart: unless-stopped
    networks:
      - nginx-proxy-nw
    environment:
      - NODE_ENV=production
      - PORT=3001

networks:
  nginx-proxy-nw:
    external: true